// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgPgmcyntEH15s5Gn4JcW-zEOgkUIhYbA',
    appId: '1:792438731850:web:f5ff3abe1b275db2e0e2b3',
    messagingSenderId: '792438731850',
    projectId: 'rates-12dcc',
    authDomain: 'rates-12dcc.firebaseapp.com',
    storageBucket: 'rates-12dcc.appspot.com',
    measurementId: 'G-MSWNB7645K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwZbaFCFiSL_takXkXSyx4njsZNwPWynU',
    appId: '1:792438731850:android:a28d26a47781ef37e0e2b3',
    messagingSenderId: '792438731850',
    projectId: 'rates-12dcc',
    storageBucket: 'rates-12dcc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBS3mf7sF89sMoKa_mUMg8d6QkXwEud8eg',
    appId: '1:792438731850:ios:622f201f07221984e0e2b3',
    messagingSenderId: '792438731850',
    projectId: 'rates-12dcc',
    storageBucket: 'rates-12dcc.appspot.com',
    iosBundleId: 'com.bev.rates',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBS3mf7sF89sMoKa_mUMg8d6QkXwEud8eg',
    appId: '1:792438731850:ios:622f201f07221984e0e2b3',
    messagingSenderId: '792438731850',
    projectId: 'rates-12dcc',
    storageBucket: 'rates-12dcc.appspot.com',
    iosBundleId: 'com.bev.rates',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgPgmcyntEH15s5Gn4JcW-zEOgkUIhYbA',
    appId: '1:792438731850:web:232f80083601537be0e2b3',
    messagingSenderId: '792438731850',
    projectId: 'rates-12dcc',
    authDomain: 'rates-12dcc.firebaseapp.com',
    storageBucket: 'rates-12dcc.appspot.com',
    measurementId: 'G-0J1ZPM4DLZ',
  );

}